#!/bin/sh

set -e

if [ $# -le 1 ]; then
    echo "Usage: make_isrs.sh <isrs_gen.c> <isrs_gen.inc>"
    exit 1
fi

ISRS_GEN_C=$1
ISRS_GEN_INC=$2

ISRS_WITH_ERROR_CODE="8 10 11 12 13 14 17 21 29 30"

# C code
#
# Style:
# void __attribute__((cdecl)) ISR0();
# void __attribute__((cdecl)) ISR1();
# void __attribute__((cdecl)) ISR2();
# 
# // ... All the way to 255 ...
# 
# void __attribute__((cdecl)) ISR255();
# 
# void ISR_RegisterGates() {
#     IDT_AddEntry(0, ISR0, GDT_CODE_SEGMENT, IDT_ATTRIBUTE_DPL0 | IDT_ATTRIBUTE_32BIT_INT);
#     IDT_AddEntry(1, ISR1, GDT_CODE_SEGMENT, IDT_ATTRIBUTE_DPL0 | IDT_ATTRIBUTE_32BIT_INT);
#     IDT_AddEntry(2, ISR2, GDT_CODE_SEGMENT, IDT_ATTRIBUTE_DPL0 | IDT_ATTRIBUTE_32BIT_INT);
# 
#     // ...
# 
#     IDT_AddEntry(255, ISR255, GDT_CODE_SEGMENT, IDT_ATTRIBUTE_DPL0 | IDT_ATTRIBUTE_32BIT_INT);
# }

echo "// This file was autogenerated with $0" > $ISRS_GEN_C
echo "#include \"idt.h\"" >> $ISRS_GEN_C
echo "#include \"isr.h\"" >> $ISRS_GEN_C
echo "#include \"gdt.h\"" >> $ISRS_GEN_C
echo "" >> $ISRS_GEN_C

for i in $(seq 0 255); do
    echo "void __attribute__((cdecl)) ISR${i}();" >> $ISRS_GEN_C
done

echo "" >> $ISRS_GEN_C
echo "void ISR_RegisterGates() {" >> $ISRS_GEN_C

for i in $(seq 0 255); do
    echo "  IDT_AddEntry(${i}, ISR${i}, GDT_CODE_SEGMENT, IDT_ATTRIBUTE_DPL0 | IDT_ATTRIBUTE_32BIT_INT);" >> $ISRS_GEN_C
done

echo "}" >> $ISRS_GEN_C

# ASM code
#
# Style:
# ISR_NOERRORCODE 0
# ISR_NOERRORCODE 1
# ISR_NOERRORCODE 2
# ISR_NOERRORCODE 3
# ISR_NOERRORCODE 4
# ISR_NOERRORCODE 5
# ISR_NOERRORCODE 6
# ISR_NOERRORCODE 7
# ISR_ERRORCODE   8
#
# ; ... All the way to 255 ...
# 
# ISR_NOERRORCODE 255


echo "; This file was autogenerated with $0" > $ISRS_GEN_INC
echo "" >> $ISRS_GEN_INC

for i in $(seq 0 255); do
    if echo "$ISRS_WITH_ERROR_CODE" | grep -q "\b${i}\b"; then
        echo "ISR_ERRORCODE   ${i}" >> $ISRS_GEN_INC
    else
        echo "ISR_NOERRORCODE ${i}" >> $ISRS_GEN_INC
    fi

done
